### ISSUE TITLE
Add the ability to map multiple remote locations to corresponding local locations

### ISSUE THREAD

**Issue by justinross** [ThatOdieGuy/SeedboxSync#15]
i.e.: 
`Seedbox '\movies' => local 'c:\potatomovies'` 

or

`Seedbox '\tv' => local 'c:\dronefactory'`

A nice bonus of this could be connecting each remote location to specific actions (like notifying Sonarr or CPotato), since, presumably, they each don't care about the other's files, and could get confused.

**Comment by justinross** [comment]
Love it

**Comment by ThatOdieGuy** [comment]
DONE.
